name "vslinko"
maintainer "Vyacheslav Slinko"
maintainer_email "vyacheslav.slinko@gmail.com"
license "MIT"
description "My *nix user environment"
version "0.1.0"

recipe "vslinko", "Prepare my *nix user environment"
recipe "vslinko::git", "Configure git"
recipe "vslinko::ssh", "Configure ssh"
recipe "vslinko::vim", "Configure vim"
recipe "vslinko::zsh", "Configure zsh"
